### ISSUE TITLE
duplicate "css-child-match-root" attribute at line 404 in "axs.rng"

### ISSUE THREAD

**Issue by honomijr** [AntennaHouse/ahfsettings#1]
Please note that there seems to be an error in "axs.rng". It contains a duplicate "css-child-match-root" attribute at line 404. Deleting the duplicate code below fixes the issue:

    <optional>
      <attribute name="css-child-match-root">
        <ref name="ah.boolean"/>
      </attribute>
    </optional>

**Comment by tgraham-antenna** [comment]
Fixed last March in 5990aaf. Included in 7.3.4 release.
